# Generated by Django 2.2 on 2019-04-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['status'], 'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AddField(
            model_name='status',
            name='code',
            field=models.CharField(default=1, max_length=5, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Status'),
        ),
    ]
