# Generated by Django 2.2 on 2019-04-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20190425_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
    ]
